data = "    language"
# new = data.lower()
# new = data.upper()
# new = data.capitalize()
# new = data.isalpha()
# new = data.isdigit()
# new = data.isalnum()
# new = data.casefold()
# new = data.center(20,"*")
# new = data.ljust(20,"*")
# new = data.rjust(20,"*")
# new = data.join("SUR")
# new = data.swapcase()
new = data.strip()
print(new)